#!/usr/bin/env python3
"""Generate a reviewable SQL script that creates a read-only MySQL user for
mysql-mcp-gateway, with column-level GRANTs on any table containing a column
you want permanently hidden (e.g. users.password).

This script never executes anything against your database. It only runs
read-only introspection queries (via the `mysql` CLI) to discover table and
column names, then writes a .sql file for you to review and run yourself.

Usage (interactive):
    python3 generate-grants.py

Usage (non-interactive):
    python3 generate-grants.py \\
        --host 127.0.0.1 --port 3306 \\
        --admin-user root --schema mydb \\
        --exclude users.password --exclude users.remember_token \\
        --out grants.generated.sql
"""
import argparse
import getpass
import secrets
import string
import subprocess
import sys

MYSQL_USER = "ai_readonly"


def run_mysql_query(host, port, admin_user, admin_pass, sql):
    """Run a single SQL statement via the mysql CLI and return tab-separated rows."""
    cmd = [
        "mysql",
        "-h", host,
        "-P", str(port),
        "-u", admin_user,
        "-N",  # no column headers
        "-B",  # tab-separated batch output
        "-e", sql,
    ]
    env = {"MYSQL_PWD": admin_pass} if admin_pass else {}
    import os
    full_env = {**os.environ, **env}
    result = subprocess.run(cmd, capture_output=True, text=True, env=full_env)
    if result.returncode != 0:
        print(f"mysql query failed: {result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)
    return [line for line in result.stdout.splitlines() if line]


def generate_strong_password(length=20):
    """Generate a password satisfying MySQL's default validate_password STRONG policy:
    12+ chars, upper, lower, digit, special char."""
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*-_="
    while True:
        pwd = "".join(secrets.choice(alphabet) for _ in range(length))
        if (
            any(c.islower() for c in pwd)
            and any(c.isupper() for c in pwd)
            and any(c.isdigit() for c in pwd)
            and any(c in "!@#$%^&*-_=" for c in pwd)
        ):
            return pwd


def parse_args():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--host", default="127.0.0.1")
    p.add_argument("--port", type=int, default=3306)
    p.add_argument("--admin-user", default="root")
    p.add_argument("--schema", help="Database/schema name to grant access to")
    p.add_argument(
        "--exclude",
        action="append",
        default=[],
        metavar="table.column",
        help="A table.column to exclude from the grant (repeatable, e.g. --exclude users.password)",
    )
    p.add_argument("--gateway-user", default=MYSQL_USER, help="MySQL username to create (default: ai_readonly)")
    p.add_argument("--out", default="grants.generated.sql")
    return p.parse_args()


def main():
    args = parse_args()

    schema = args.schema or input("Database/schema name: ").strip()
    if not args.exclude:
        print("Enter table.column pairs to exclude (e.g. users.password), one per line.")
        print("Leave blank and press Enter when done.")
        while True:
            line = input("  exclude> ").strip()
            if not line:
                break
            args.exclude.append(line)

    admin_pass = getpass.getpass(f"Password for admin user '{args.admin_user}' (used only to read table/column names, not stored): ")

    excludes_by_table = {}
    for pair in args.exclude:
        if "." not in pair:
            print(f"Skipping invalid --exclude value (expected table.column): {pair}", file=sys.stderr)
            continue
        table, column = pair.split(".", 1)
        excludes_by_table.setdefault(table, set()).add(column)

    tables = run_mysql_query(
        args.host, args.port, args.admin_user, admin_pass,
        f"SELECT table_name FROM information_schema.tables WHERE table_schema = '{schema}' AND table_type = 'BASE TABLE'",
    )
    if not tables:
        print(f"No tables found in schema '{schema}' - check the schema name and admin credentials.", file=sys.stderr)
        sys.exit(1)

    gateway_password = generate_strong_password()

    lines = []
    lines.append(f"-- Generated by mysql-mcp-gateway/scripts/generate-grants.py")
    lines.append(f"-- Review this file before running it. It creates a SELECT-only user")
    lines.append(f"-- with no INSERT/UPDATE/DELETE/DROP/ALTER privileges anywhere.")
    lines.append("")
    lines.append(
        f"CREATE USER '{args.gateway_user}'@'%' IDENTIFIED WITH caching_sha2_password BY '{gateway_password}';"
    )
    lines.append("")

    for table in sorted(tables):
        excluded_columns = excludes_by_table.get(table)
        if not excluded_columns:
            lines.append(f"GRANT SELECT ON `{schema}`.`{table}` TO '{args.gateway_user}'@'%';")
            continue

        all_columns = run_mysql_query(
            args.host, args.port, args.admin_user, admin_pass,
            f"SELECT column_name FROM information_schema.columns "
            f"WHERE table_schema = '{schema}' AND table_name = '{table}' ORDER BY ordinal_position",
        )
        allowed_columns = [c for c in all_columns if c not in excluded_columns]
        missing = excluded_columns - set(all_columns)
        if missing:
            print(
                f"Warning: table '{table}' has no column(s) named {sorted(missing)} - check for typos.",
                file=sys.stderr,
            )
        if not allowed_columns:
            print(
                f"Warning: every column in '{table}' is excluded - skipping this table entirely.",
                file=sys.stderr,
            )
            continue
        column_list = ", ".join(f"`{c}`" for c in allowed_columns)
        lines.append(f"GRANT SELECT ({column_list}) ON `{schema}`.`{table}` TO '{args.gateway_user}'@'%';")

    lines.append("")
    lines.append("FLUSH PRIVILEGES;")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\nWrote {args.out} - review it, then run it yourself, e.g.:")
    print(f"    mysql -h {args.host} -P {args.port} -u {args.admin_user} -p < {args.out}")
    print(f"\nGenerated password for '{args.gateway_user}': {gateway_password}")
    print("Save this - it's needed by scripts/generate-env.py next. It is not stored anywhere else.")


if __name__ == "__main__":
    main()
